export const PermissionNames = {
  OrganizationView: 'organization.view',
  OrganizationManage: 'organization.manage',
  UsersView: 'users.view',
  UsersManage: 'users.manage',
  RolesView: 'roles.view',
  RolesManage: 'roles.manage',
  AuditView: 'audit.view',
  DocumentsView: 'documents.view',
  DocumentsUpload: 'documents.upload',
  DocumentsValidate: 'documents.validate',
  AccountingView: 'accounting.view',
  AccountingManage: 'accounting.manage',
  AccountingPost: 'accounting.post',
  CompanyProfileView: 'company_profile.view',
  CompanyProfileManage: 'company_profile.manage',
  FiscalYearsView: 'fiscal_years.view',
  FiscalYearsManage: 'fiscal_years.manage',
  FiscalYearsClose: 'fiscal_years.close',
  ChartOfAccountsView: 'chart_of_accounts.view',
  ChartOfAccountsManage: 'chart_of_accounts.manage',
  DossiersView: 'dossiers.view',
  DossiersCreate: 'dossiers.create',
  DossiersManage: 'dossiers.manage',
  DossiersAssign: 'dossiers.assign',
  DossierContactsManage: 'dossiers.contacts.manage',
  ObligationsView: 'obligations.view',
  ObligationsManage: 'obligations.manage',
  ObligationsValidate: 'obligations.validate',
  ObligationsFile: 'obligations.file',
  ObligationTemplatesManage: 'obligation_templates.manage',
  TasksView: 'tasks.view',
  TasksManage: 'tasks.manage',
  TasksAssign: 'tasks.assign',
  TasksValidate: 'tasks.validate',
  NotificationsView: 'notifications.view',
  NotificationsManage: 'notifications.manage',
  DeclarationsView: 'declarations.view',
  DeclarationsManage: 'declarations.manage',
  DeclarationsValidate: 'declarations.validate',
  ReportsView: 'reports.view',
  BillingView: 'billing.view',
  BillingManage: 'billing.manage',
  TimeTrackingView: 'time_tracking.view',
  TimeTrackingManage: 'time_tracking.manage',
  TimeTrackingApprove: 'time_tracking.approve',
  TeamCostsManage: 'team_costs.manage',
  ProfitabilityView: 'profitability.view',
  PayrollView: 'payroll.view',
  PayrollManage: 'payroll.manage',
  PayrollValidate: 'payroll.validate',
  FiscalSettingsView: 'fiscal_settings.view',
  FiscalSettingsManage: 'fiscal_settings.manage',
  BusinessInvoicesView: 'business_invoices.view',
  BusinessInvoicesManage: 'business_invoices.manage',
  BusinessInvoicesValidate: 'business_invoices.validate',
  ThirdPartiesView: 'third_parties.view',
  ThirdPartiesManage: 'third_parties.manage',
  PaymentsView: 'payments.view',
  PaymentsManage: 'payments.manage',
  BankReconciliationView: 'bank_reconciliation.view',
  BankReconciliationManage: 'bank_reconciliation.manage',
  BankReconciliationValidate: 'bank_reconciliation.validate',
  FixedAssetsView: 'fixed_assets.view',
  FixedAssetsManage: 'fixed_assets.manage',
  FixedAssetsValidate: 'fixed_assets.validate',
  PeriodClosingView: 'period_closing.view',
  PeriodClosingManage: 'period_closing.manage',
  PeriodClosingValidate: 'period_closing.validate',
  FinancialStatementsView: 'financial_statements.view',
  FinancialStatementsManage: 'financial_statements.manage',
  FinancialStatementsValidate: 'financial_statements.validate',
  QualityAssuranceView: 'quality_assurance.view',
  ForeignTradeView: 'foreign_trade.view',
  ForeignTradeManage: 'foreign_trade.manage',
  ForeignTradePost: 'foreign_trade.post',
  ElectronicInvoicesView: 'electronic_invoices.view',
  ElectronicInvoicesManage: 'electronic_invoices.manage',
  ElectronicInvoicesSubmit: 'electronic_invoices.submit',
  ElectronicInvoicesConfigure: 'electronic_invoices.configure',
  ClientPortalView: 'client_portal.view',
  ClientPortalMessage: 'client_portal.message',
} as const;

export const allPermissions = Object.values(PermissionNames);

export const permissionSeed = [
  [
    PermissionNames.OrganizationView,
    'Consulter les paramètres de l’organisation',
  ],
  [
    PermissionNames.OrganizationManage,
    'Gérer les paramètres de l’organisation',
  ],
  [PermissionNames.UsersView, 'Consulter les membres de l’organisation'],
  [
    PermissionNames.UsersManage,
    'Inviter et gérer les membres de l’organisation',
  ],
  [PermissionNames.RolesView, 'Consulter les rôles et les permissions'],
  [
    PermissionNames.RolesManage,
    'Créer des rôles et modifier leurs permissions',
  ],
  [PermissionNames.AuditView, 'Consulter le journal d’audit'],
  [PermissionNames.DocumentsView, 'Consulter les documents comptables'],
  [PermissionNames.DocumentsUpload, 'Téléverser des documents comptables'],
  [
    PermissionNames.DocumentsValidate,
    'Valider les données extraites des documents',
  ],
  [PermissionNames.AccountingView, 'Consulter les données comptables'],
  [
    PermissionNames.AccountingManage,
    'Créer et modifier les données comptables',
  ],
  [PermissionNames.AccountingPost, 'Comptabiliser les écritures'],
  [
    PermissionNames.CompanyProfileView,
    'Consulter les informations légales de la société',
  ],
  [
    PermissionNames.CompanyProfileManage,
    'Gérer les informations légales de la société',
  ],
  [PermissionNames.FiscalYearsView, 'Consulter les exercices comptables'],
  [
    PermissionNames.FiscalYearsManage,
    'Créer et gérer les exercices comptables',
  ],
  [PermissionNames.FiscalYearsClose, 'Clôturer les exercices comptables'],
  [PermissionNames.ChartOfAccountsView, 'Consulter le plan comptable'],
  [
    PermissionNames.ChartOfAccountsManage,
    'Créer et gérer les comptes comptables',
  ],
  [PermissionNames.DossiersView, 'Consulter les dossiers clients autorisés'],
  [PermissionNames.DossiersCreate, 'Créer et archiver les dossiers clients'],
  [PermissionNames.DossiersManage, 'Modifier les dossiers clients autorisés'],
  [
    PermissionNames.DossiersAssign,
    'Affecter les collaborateurs et consulter tous les dossiers',
  ],
  [
    PermissionNames.DossierContactsManage,
    'Gérer les contacts des dossiers clients autorisés',
  ],
  [PermissionNames.ObligationsView, 'Consulter les obligations des dossiers'],
  [
    PermissionNames.ObligationsManage,
    'Préparer les obligations des dossiers autorisés',
  ],
  [
    PermissionNames.ObligationsValidate,
    'Valider ou rejeter les obligations préparées',
  ],
  [PermissionNames.ObligationsFile, 'Marquer une obligation comme déposée'],
  [
    PermissionNames.ObligationTemplatesManage,
    "Gérer les modèles et règles d'obligations",
  ],
  [PermissionNames.TasksView, 'Consulter les tâches des dossiers autorisés'],
  [
    PermissionNames.TasksManage,
    'Créer et préparer les tâches des dossiers autorisés',
  ],
  [PermissionNames.TasksAssign, 'Affecter les tâches aux collaborateurs'],
  [PermissionNames.TasksValidate, 'Valider ou rejeter les tâches préparées'],
  [PermissionNames.NotificationsView, 'Consulter ses notifications'],
  [
    PermissionNames.NotificationsManage,
    'Générer et administrer les notifications',
  ],
  [
    PermissionNames.DeclarationsView,
    'Consulter les feuilles de déclaration mensuelle',
  ],
  [
    PermissionNames.DeclarationsManage,
    'Préparer les feuilles de déclaration mensuelle',
  ],
  [
    PermissionNames.DeclarationsValidate,
    'Valider et figer les feuilles de déclaration',
  ],
  [PermissionNames.ReportsView, 'Consulter les rapports comptables'],
  [PermissionNames.BillingView, 'Consulter les honoraires du cabinet'],
  [
    PermissionNames.BillingManage,
    'Créer les factures et enregistrer les règlements',
  ],
  [
    PermissionNames.TimeTrackingView,
    'Consulter les temps de travail autorisés',
  ],
  [
    PermissionNames.TimeTrackingManage,
    'Saisir et soumettre son temps de travail',
  ],
  [
    PermissionNames.TimeTrackingApprove,
    'Approuver ou rejeter les temps de travail',
  ],
  [
    PermissionNames.TeamCostsManage,
    'Gérer les rémunérations et coûts employeur du cabinet',
  ],
  [
    PermissionNames.ProfitabilityView,
    'Consulter la rentabilité par client et collaborateur',
  ],
  [PermissionNames.PayrollView, 'Consulter les salariés et la paie'],
  [PermissionNames.PayrollManage, 'Préparer les traitements de paie'],
  [PermissionNames.PayrollValidate, 'Valider les traitements de paie'],
  [
    PermissionNames.FiscalSettingsView,
    'Consulter les paramètres fiscaux et sociaux applicables',
  ],
  [
    PermissionNames.FiscalSettingsManage,
    'Créer et versionner les paramètres fiscaux et sociaux',
  ],
  [
    PermissionNames.BusinessInvoicesView,
    'Consulter les factures d’achat et de vente',
  ],
  [
    PermissionNames.BusinessInvoicesManage,
    'Créer et modifier les factures d’achat et de vente',
  ],
  [
    PermissionNames.BusinessInvoicesValidate,
    'Valider et générer les écritures des factures',
  ],
  [PermissionNames.ThirdPartiesView, 'Consulter les clients et fournisseurs'],
  [PermissionNames.ThirdPartiesManage, 'Gérer les clients et fournisseurs'],
  [PermissionNames.PaymentsView, 'Consulter les règlements des tiers'],
  [PermissionNames.PaymentsManage, 'Préparer les règlements et affectations'],
  [
    PermissionNames.BankReconciliationView,
    'Consulter les comptes, relevés et rapprochements bancaires',
  ],
  [
    PermissionNames.BankReconciliationManage,
    'Importer les relevés et préparer les rapprochements bancaires',
  ],
  [
    PermissionNames.BankReconciliationValidate,
    'Valider et figer les rapprochements bancaires',
  ],
  [
    PermissionNames.FixedAssetsView,
    'Consulter le registre des immobilisations',
  ],
  [
    PermissionNames.FixedAssetsManage,
    'Gérer les immobilisations et préparer les amortissements',
  ],
  [
    PermissionNames.FixedAssetsValidate,
    'Comptabiliser et clôturer les amortissements',
  ],
  [
    PermissionNames.PeriodClosingView,
    'Consulter les périodes et travaux de clôture comptable',
  ],
  [
    PermissionNames.PeriodClosingManage,
    'Préparer les écritures de régularisation comptable',
  ],
  [
    PermissionNames.PeriodClosingValidate,
    'Verrouiller les périodes et clôturer les exercices comptables',
  ],
  [
    PermissionNames.FinancialStatementsView,
    'Consulter et exporter les états financiers des dossiers',
  ],
  [
    PermissionNames.FinancialStatementsManage,
    'Configurer le mapping et préparer les états financiers',
  ],
  [
    PermissionNames.FinancialStatementsValidate,
    'Valider et figer les états financiers définitifs',
  ],
  [
    PermissionNames.QualityAssuranceView,
    'Consulter les contrôles qualité des dossiers clients',
  ],
  [
    PermissionNames.ForeignTradeView,
    'Consulter les devises et opÃ©rations de commerce extÃ©rieur',
  ],
  [
    PermissionNames.ForeignTradeManage,
    'GÃ©rer les taux, attestations et opÃ©rations de commerce extÃ©rieur',
  ],
  [
    PermissionNames.ForeignTradePost,
    'Comptabiliser les opÃ©rations et Ã©carts de change',
  ],
  [
    PermissionNames.ElectronicInvoicesView,
    'Consulter les factures Ã©lectroniques TTN',
  ],
  [
    PermissionNames.ElectronicInvoicesManage,
    'PrÃ©parer les factures Ã©lectroniques TTN',
  ],
  [
    PermissionNames.ElectronicInvoicesSubmit,
    'Transmettre ou simuler la transmission TTN',
  ],
  [
    PermissionNames.ElectronicInvoicesConfigure,
    'Configurer le raccordement TTN du dossier',
  ],
  [PermissionNames.ClientPortalView, 'Accéder au portail client sécurisé'],
  [
    PermissionNames.ClientPortalMessage,
    'Échanger des messages dans le portail client',
  ],
] as const;

export const SystemRoleNames = {
  Owner: 'Propriétaire',
  Collaborator: 'Collaborateur',
  ClientPortal: 'Portail client',
} as const;

export const ownerPermissions = allPermissions;
export const collaboratorPermissions = [
  PermissionNames.OrganizationView,
  PermissionNames.UsersView,
  PermissionNames.RolesView,
  PermissionNames.DocumentsView,
  PermissionNames.DocumentsUpload,
  PermissionNames.DocumentsValidate,
  PermissionNames.AccountingView,
  PermissionNames.AccountingManage,
  PermissionNames.CompanyProfileView,
  PermissionNames.FiscalYearsView,
  PermissionNames.ChartOfAccountsView,
  PermissionNames.DossiersView,
  PermissionNames.DossiersManage,
  PermissionNames.DossierContactsManage,
  PermissionNames.ObligationsView,
  PermissionNames.ObligationsManage,
  PermissionNames.TasksView,
  PermissionNames.TasksManage,
  PermissionNames.NotificationsView,
  PermissionNames.DeclarationsView,
  PermissionNames.DeclarationsManage,
  PermissionNames.ReportsView,
  PermissionNames.BillingView,
  PermissionNames.TimeTrackingView,
  PermissionNames.TimeTrackingManage,
  PermissionNames.PayrollView,
  PermissionNames.PayrollManage,
  PermissionNames.FiscalSettingsView,
  PermissionNames.BusinessInvoicesView,
  PermissionNames.BusinessInvoicesManage,
  PermissionNames.ThirdPartiesView,
  PermissionNames.ThirdPartiesManage,
  PermissionNames.PaymentsView,
  PermissionNames.PaymentsManage,
  PermissionNames.BankReconciliationView,
  PermissionNames.BankReconciliationManage,
  PermissionNames.FixedAssetsView,
  PermissionNames.FixedAssetsManage,
  PermissionNames.PeriodClosingView,
  PermissionNames.PeriodClosingManage,
  PermissionNames.FinancialStatementsView,
  PermissionNames.FinancialStatementsManage,
  PermissionNames.QualityAssuranceView,
  PermissionNames.ForeignTradeView,
  PermissionNames.ForeignTradeManage,
  PermissionNames.ElectronicInvoicesView,
  PermissionNames.ElectronicInvoicesManage,
  PermissionNames.ClientPortalView,
  PermissionNames.ClientPortalMessage,
];
export const clientPortalPermissions = [
  PermissionNames.OrganizationView,
  PermissionNames.DossiersView,
  PermissionNames.DocumentsView,
  PermissionNames.DocumentsUpload,
  PermissionNames.NotificationsView,
  PermissionNames.ObligationsView,
  PermissionNames.DeclarationsView,
  PermissionNames.BillingView,
  PermissionNames.BusinessInvoicesView,
  PermissionNames.PaymentsView,
  PermissionNames.FinancialStatementsView,
  PermissionNames.ClientPortalView,
  PermissionNames.ClientPortalMessage,
];
