import { LedgerAccountType, NormalBalance } from '../database/entities';

export interface TunisianChartAccount {
  code: string;
  name: string;
  type: LedgerAccountType;
  normalBalance: NormalBalance;
  allowsPosting: boolean;
  parentCode: string | null;
}

// Nomenclature générale NC 01. Les dossiers peuvent ajouter des subdivisions
// analytiques sans modifier ce référentiel de base.
const rows: ReadonlyArray<readonly [string, string]> = [
  ['10', 'Capital'],
  ['101', 'Capital social'],
  ['1011', 'Capital souscrit - non appelé'],
  ['1012', 'Capital souscrit - appelé, non versé'],
  ['1013', 'Capital souscrit - appelé, versé'],
  ['10131', 'Capital non amorti'],
  ['10132', 'Capital amorti'],
  ['1018', 'Capital soumis à une réglementation particulière'],
  ['105', 'Fonds de dotation'],
  ['108', "Compte de l'exploitant"],
  ['109', 'Actionnaires, capital souscrit - non appelé'],
  ['11', 'Réserves et primes liées au capital'],
  ['111', 'Réserve légale'],
  ['112', 'Réserves statutaires'],
  ['117', 'Primes liées au capital'],
  ['1171', "Primes d'émission"],
  ['1172', 'Primes de fusion'],
  ['1173', "Primes d'apport"],
  ['1174', "Primes de conversion d'obligations"],
  ['1178', "Autres compléments d'apport"],
  ['118', 'Autres réserves'],
  ['1181', 'Réserves pour fonds social'],
  ['119', 'Avoirs des actionnaires'],
  ['12', 'Résultats reportés'],
  ['121', 'Résultats reportés'],
  ['128', 'Modifications comptables affectant les résultats reportés'],
  ['13', "Résultat de l'exercice"],
  ['131', 'Résultat bénéficiaire'],
  ['135', 'Résultat déficitaire'],
  ['14', 'Autres capitaux propres'],
  ['141', 'Titres soumis à des réglementations particulières'],
  [
    '142',
    'Réserves réglementées et réserves soumises à un régime fiscal particulier',
  ],
  ['1421', 'Réserves indisponibles'],
  ['143', 'Amortissements dérogatoires'],
  ['144', 'Réserve spéciale de réévaluation'],
  ['145', "Subventions d'investissement"],
  ['1451', "Subventions d'investissement"],
  ['1458', "Autres subventions d'investissement"],
  ['1459', "Subventions d'investissement inscrites aux résultats"],
  ['147', 'Compte du concédant'],
  ['15', 'Provisions pour risques et charges'],
  ['151', 'Provisions pour risques'],
  ['1511', 'Provisions pour litiges'],
  ['1512', 'Provisions pour garanties données aux clients'],
  ['1513', 'Provisions pour pertes sur marchés à achèvement futur'],
  ['1514', 'Provisions pour amendes et pénalités'],
  ['1515', 'Provisions pour pertes de change'],
  ['1518', 'Autres provisions pour risques'],
  ['152', 'Provisions pour charges à répartir sur plusieurs exercices'],
  ['153', 'Provisions pour retraites et obligations similaires'],
  ['155', 'Provisions pour impôts'],
  ['156', 'Provisions pour renouvellement des immobilisations'],
  ['158', 'Autres provisions pour charges'],
  ['16', 'Emprunts et dettes assimilées'],
  ['161', 'Emprunts obligataires'],
  ['162', 'Emprunts auprès des établissements financiers'],
  ['164', 'Emprunts auprès des associés'],
  ['165', 'Dépôts et cautionnements reçus'],
  ['166', 'Dettes rattachées à des participations'],
  ['167', 'Emprunts et dettes assortis de conditions particulières'],
  ['168', 'Autres emprunts et dettes assimilées'],
  ['1681', 'Autres emprunts'],
  ['1685', 'Crédits fournisseurs non courants'],
  ['1688', 'Intérêts courus'],
  ['17', 'Comptes de liaison des établissements et succursales'],
  ['171', 'Biens et prestations échangés entre établissements - charges'],
  ['176', 'Biens et prestations échangés entre établissements - produits'],
  ['18', 'Autres passifs non courants'],
  ['185', 'Écarts de conversion'],
  ['188', 'Autres passifs non courants'],

  ['21', 'Immobilisations incorporelles'],
  ['211', 'Investissements de recherche et de développement'],
  [
    '212',
    'Concessions, brevets, licences, marques, procédés et droits similaires',
  ],
  ['213', 'Logiciels'],
  ['214', 'Fonds commercial'],
  ['216', 'Droit au bail'],
  ['218', 'Autres immobilisations incorporelles'],
  ['22', 'Immobilisations corporelles'],
  ['221', 'Terrains'],
  ['2213', 'Terrains nus'],
  ['2214', 'Terrains aménagés'],
  ['2215', 'Terrains bâtis'],
  ['2216', 'Agencements et aménagements des terrains'],
  ['222', 'Constructions'],
  ['2221', 'Bâtiments'],
  [
    '2225',
    'Installations générales, agencements et aménagements des constructions',
  ],
  ['2226', "Ouvrages d'infrastructure"],
  ['2227', "Constructions sur sol d'autrui"],
  ['223', 'Installations techniques, matériel et outillage industriels'],
  ['2231', 'Installations techniques'],
  ['2234', 'Matériel industriel'],
  ['2235', 'Outillage industriel'],
  ['2237', 'Agencements et aménagements du matériel industriel'],
  ['224', 'Matériel de transport'],
  ['2241', 'Matériel de transport de biens'],
  ['2244', 'Matériel de transport de personnes'],
  ['228', 'Autres immobilisations corporelles'],
  ['2281', 'Installations générales, agencements et aménagements divers'],
  ['2282', 'Équipement de bureau'],
  ['2286', 'Emballages récupérables identifiables'],
  ['23', 'Immobilisations en cours'],
  ['231', 'Immobilisations incorporelles en cours'],
  ['232', 'Immobilisations corporelles en cours'],
  ['237', 'Avances et acomptes sur immobilisations incorporelles'],
  ['238', 'Avances et acomptes sur immobilisations corporelles'],
  ['24', 'Immobilisations à statut juridique particulier'],
  ['25', 'Participations et créances liées à des participations'],
  ['251', 'Titres de participation'],
  ['2511', 'Actions'],
  ['2518', 'Autres titres'],
  ['256', 'Autres formes de participation'],
  ['257', 'Créances rattachées à des participations'],
  ['2571', 'Créances rattachées à des participations - groupe'],
  ['2574', 'Créances rattachées à des participations - hors groupe'],
  ['258', 'Créances rattachées à des sociétés en participation'],
  ['26', 'Autres immobilisations financières'],
  ['261', 'Titres immobilisés'],
  ['265', 'Dépôts et cautionnements versés'],
  ['266', 'Prêts'],
  ['267', 'Créances financières diverses'],
  ['27', 'Autres actifs non courants'],
  ['271', 'Frais préliminaires'],
  ['272', 'Charges à répartir'],
  ['273', "Frais d'émission et primes de remboursement des emprunts"],
  ['275', 'Écarts de conversion'],
  ['278', 'Autres actifs non courants'],
  ['28', 'Amortissements des immobilisations'],
  ['281', 'Amortissements des immobilisations incorporelles'],
  ['2811', 'Amortissements des investissements de recherche et développement'],
  [
    '2812',
    'Amortissements des concessions, brevets, licences et droits similaires',
  ],
  ['2813', 'Amortissements des logiciels'],
  ['2818', 'Amortissements des autres immobilisations incorporelles'],
  ['282', 'Amortissements des immobilisations corporelles'],
  ['2822', 'Amortissements des constructions'],
  [
    '2823',
    'Amortissements des installations techniques, matériel et outillage',
  ],
  ['2824', 'Amortissements du matériel de transport'],
  ['2828', 'Amortissements des autres immobilisations corporelles'],
  ['29', 'Provisions pour dépréciation des actifs immobilisés'],
  ['291', 'Provisions pour dépréciation des immobilisations incorporelles'],
  ['292', 'Provisions pour dépréciation des immobilisations corporelles'],
  ['293', 'Provisions pour dépréciation des immobilisations en cours'],
  [
    '294',
    'Provisions pour dépréciation des immobilisations à statut particulier',
  ],
  ['295', 'Provisions pour dépréciation des participations et créances liées'],
  [
    '296',
    'Provisions pour dépréciation des autres immobilisations financières',
  ],

  ['31', 'Matières premières et fournitures liées'],
  ['311', 'Matières premières'],
  ['313', 'Fournitures'],
  ['317', 'Autres matières et fournitures'],
  ['32', 'Autres approvisionnements'],
  ['321', 'Matières consommables'],
  ['322', 'Fournitures consommables'],
  ['326', 'Emballages'],
  ['327', 'Autres approvisionnements'],
  ['33', 'En-cours de production de biens'],
  ['331', 'Produits en cours'],
  ['335', 'Travaux en cours'],
  ['34', 'En-cours de production de services'],
  ['341', 'Études en cours'],
  ['345', 'Prestations de services en cours'],
  ['35', 'Stocks de produits'],
  ['351', 'Produits intermédiaires'],
  ['355', 'Produits finis'],
  ['357', 'Produits résiduels'],
  ['37', 'Stocks de marchandises'],
  ['39', 'Provisions pour dépréciation des stocks'],
  ['391', 'Provisions pour dépréciation des matières premières'],
  ['392', 'Provisions pour dépréciation des autres approvisionnements'],
  ['393', 'Provisions pour dépréciation des en-cours de biens'],
  ['394', 'Provisions pour dépréciation des en-cours de services'],
  ['395', 'Provisions pour dépréciation des produits'],
  ['397', 'Provisions pour dépréciation des marchandises'],

  ['40', 'Fournisseurs et comptes rattachés'],
  ['401', "Fournisseurs d'exploitation"],
  ['4011', 'Fournisseurs - achats de biens ou prestations'],
  ['4017', 'Fournisseurs - retenues de garantie'],
  ['403', "Fournisseurs d'exploitation - effets à payer"],
  ['404', "Fournisseurs d'immobilisations"],
  ['4041', "Fournisseurs - achats d'immobilisations"],
  ['4047', "Fournisseurs d'immobilisations - retenues de garantie"],
  ['405', "Fournisseurs d'immobilisations - effets à payer"],
  ['408', 'Fournisseurs - factures non parvenues'],
  ['4081', "Fournisseurs d'exploitation - factures non parvenues"],
  ['4084', "Fournisseurs d'immobilisations - factures non parvenues"],
  ['409', 'Fournisseurs débiteurs'],
  ['4091', 'Fournisseurs - avances et acomptes versés'],
  ['4096', 'Fournisseurs - créances pour emballages à rendre'],
  ['4097', 'Fournisseurs - autres avoirs'],
  ['4098', 'Rabais, remises et ristournes à obtenir'],
  ['41', 'Clients et comptes rattachés'],
  ['411', 'Clients'],
  ['413', 'Clients - effets à recevoir'],
  ['416', 'Clients douteux ou litigieux'],
  ['417', 'Créances sur travaux non encore facturables'],
  ['418', 'Clients - produits non encore facturés'],
  ['4181', 'Clients - factures à établir'],
  ['419', 'Clients créditeurs'],
  ['4191', 'Clients - avances et acomptes reçus'],
  ['4196', 'Clients - dettes pour emballages consignés'],
  ['4197', 'Clients - autres avoirs'],
  ['4198', 'Rabais, remises et ristournes à accorder'],
  ['42', 'Personnel et comptes rattachés'],
  ['421', 'Personnel - avances et acomptes'],
  ['422', 'Comités et autres organismes sociaux'],
  ['423', 'Personnel - rémunérations dues'],
  ['425', 'Personnel - oppositions sur salaires'],
  ['426', 'Personnel - dépôts'],
  ['427', 'Personnel - charges à payer et produits à recevoir'],
  ['4272', 'Dettes provisionnées pour congés à payer'],
  ['428', 'Personnel - autres comptes'],
  ['43', 'État et collectivités publiques'],
  ['431', 'État - subventions à recevoir'],
  ['432', 'État - impôts et taxes retenus à la source'],
  ['433', 'Opérations particulières avec l’État'],
  ['434', 'État - impôts sur les bénéfices'],
  ['435', 'Obligations cautionnées'],
  ['436', "État - taxes sur le chiffre d'affaires"],
  ['4365', "Taxes sur le chiffre d'affaires à décaisser"],
  ['43651', 'TVA à payer'],
  ['43658', "Autres taxes sur le chiffre d'affaires"],
  ['4366', "Taxes sur le chiffre d'affaires déductibles"],
  ['43662', 'TVA sur immobilisations'],
  ['43663', "TVA transférée par d'autres entreprises"],
  ['43666', 'TVA sur autres biens et services'],
  ['43667', 'Crédit de TVA à reporter'],
  ['43668', "Autres taxes sur le chiffre d'affaires déductibles"],
  ['4367', "Taxes sur le chiffre d'affaires collectées"],
  ['43671', 'TVA collectée'],
  ['436711', 'TVA collectée sur les débits'],
  ['436712', 'TVA collectée sur les encaissements'],
  ['43678', "Autres taxes sur le chiffre d'affaires collectées"],
  ['4368', "Taxes sur le chiffre d'affaires à régulariser ou en attente"],
  ['437', 'Autres impôts, taxes et versements assimilés'],
  ['438', 'État - charges à payer et produits à recevoir'],
  ['4382', 'Charges fiscales sur congés à payer'],
  ['4386', 'Autres charges fiscales à payer'],
  ['4387', 'Produits fiscaux à recevoir'],
  ['44', 'Sociétés du groupe et associés'],
  ['441', 'Groupe'],
  ['4411', 'Créances et intérêts courus'],
  ['4412', 'Dettes et intérêts à payer'],
  ['442', 'Associés - comptes courants'],
  ['4421', 'Associés - principal'],
  ['4428', 'Associés - intérêts courus'],
  ['446', 'Associés - opérations sur le capital'],
  ['447', 'Associés - dividendes à payer'],
  ['448', 'Associés - opérations faites en commun'],
  ['4481', 'Opérations courantes'],
  ['4488', 'Intérêts courus'],
  ['45', 'Débiteurs divers et créditeurs divers'],
  ['452', "Créances sur cessions d'immobilisations"],
  ['453', 'Sécurité sociale et autres organismes sociaux'],
  ['4531', 'Organismes sociaux'],
  ['45311', 'CNSS'],
  ['45318', 'Autres organismes sociaux'],
  ['4538', 'Organismes sociaux - charges à payer et produits à recevoir'],
  ['45382', 'Charges sociales sur congés à payer'],
  ['45386', 'Autres charges sociales à payer'],
  ['45387', 'Produits sociaux à recevoir'],
  ['454', 'Dettes sur acquisitions de valeurs mobilières de placement'],
  ['455', 'Créances sur cessions de valeurs mobilières de placement'],
  ['457', 'Autres comptes débiteurs ou créditeurs'],
  ['458', 'Diverses charges à payer et produits à recevoir'],
  ['4586', 'Charges à payer'],
  ['4587', 'Produits à recevoir'],
  ['46', "Comptes transitoires ou d'attente"],
  ['461', "Compte d'attente"],
  ['465', 'Différences de conversion sur éléments courants'],
  ['4651', 'Différences de conversion actif'],
  ['4652', 'Différences de conversion passif'],
  ['468', 'Autres comptes transitoires'],
  ['47', 'Comptes de régularisation'],
  ['471', "Charges constatées d'avance"],
  ['472', "Produits constatés d'avance"],
  ['478', 'Comptes de répartition périodique de charges et produits'],
  ['4786', 'Charges à répartir'],
  ['4787', 'Produits à répartir'],
  ['48', 'Provisions courantes pour risques et charges'],
  ['481', 'Provisions courantes pour risques'],
  ['482', 'Provisions courantes pour charges'],
  ['49', 'Provisions pour dépréciation des comptes de tiers'],
  ['491', 'Provisions pour dépréciation des comptes clients'],
  ['494', 'Provisions pour dépréciation des comptes du groupe et associés'],
  ['495', 'Provisions pour dépréciation des débiteurs divers'],

  ['50', 'Emprunts et autres dettes financières courants'],
  ['501', 'Emprunts courants liés au cycle d’exploitation'],
  ['505', 'Échéances à moins d’un an sur emprunts non courants'],
  ['506', 'Concours bancaires courants'],
  ['508', 'Intérêts courus'],
  ['51', 'Prêts et autres créances financières courants'],
  ['511', 'Prêts courants liés au cycle d’exploitation'],
  ['516', 'Échéances à moins d’un an sur prêts non courants'],
  ['518', 'Intérêts courus'],
  ['52', 'Placements courants'],
  ['523', 'Actions'],
  ['524', 'Autres titres conférant un droit de propriété'],
  ['525', 'Obligations et bons émis par la société et rachetés'],
  ['526', 'Obligations'],
  ['527', 'Bons du Trésor et bons de caisse à court terme'],
  ['528', 'Autres placements courants et créances assimilées'],
  ['53', 'Banques, établissements financiers et assimilés'],
  ['531', 'Valeurs à encaisser'],
  ['5311', "Coupons échus à l'encaissement"],
  ['5312', 'Chèques à encaisser'],
  ['5313', "Effets à l'encaissement"],
  ['5314', "Effets à l'escompte"],
  ['532', 'Banques'],
  ['5321', 'Comptes bancaires en dinars'],
  ['5324', 'Comptes bancaires en devises'],
  ['534', 'Comptes courants postaux'],
  ['535', 'Comptes au Trésor'],
  ['537', 'Autres organismes financiers'],
  ['54', 'Caisse'],
  ['541', 'Caisse siège social'],
  ['5411', 'Caisse en dinars'],
  ['5414', 'Caisse en devises'],
  ['542', 'Caisses succursales'],
  ['55', "Régies d'avances et accréditifs"],
  ['58', 'Virements internes'],
  ['59', 'Provisions pour dépréciation des comptes financiers'],
  ['592', 'Provisions pour dépréciation des placements courants'],

  ['60', 'Achats'],
  ['601', 'Achats stockés - matières premières et fournitures liées'],
  ['602', 'Achats stockés - autres approvisionnements'],
  ['6021', 'Matières consommables'],
  ['6022', 'Fournitures consommables'],
  ['6026', 'Emballages'],
  ['603', 'Variation des stocks - approvisionnements et marchandises'],
  ['6031', 'Variation des stocks de matières premières'],
  ['6032', 'Variation des stocks des autres approvisionnements'],
  ['6037', 'Variation des stocks de marchandises'],
  ['604', "Achats d'études et de prestations de services"],
  ['605', 'Achats de matériel, équipements et travaux'],
  ['606', 'Achats non stockés de matières et fournitures'],
  ['607', 'Achats de marchandises'],
  ['608', 'Achats liés à une modification comptable ou activité abandonnée'],
  ['609', 'Rabais, remises et ristournes obtenus sur achats'],
  ['61', 'Services extérieurs'],
  ['611', 'Sous-traitance générale'],
  ['612', "Redevances pour utilisation d'immobilisations concédées"],
  ['613', 'Locations'],
  ['614', 'Charges locatives et de copropriété'],
  ['615', 'Entretien et réparations'],
  ['616', "Primes d'assurances"],
  ['617', 'Études, recherches et documentation'],
  ['618', 'Autres services extérieurs'],
  ['62', 'Autres services extérieurs'],
  ['621', 'Personnel extérieur à l’entreprise'],
  ['622', 'Rémunérations d’intermédiaires et honoraires'],
  ['623', 'Publicité, publications et relations publiques'],
  ['624', 'Transports de biens et transports collectifs du personnel'],
  ['625', 'Déplacements, missions et réceptions'],
  ['626', 'Frais postaux et frais de télécommunications'],
  ['627', 'Services bancaires et assimilés'],
  ['628', 'Autres services extérieurs'],
  ['63', 'Charges diverses ordinaires'],
  [
    '631',
    'Redevances pour concessions, brevets, licences et droits similaires',
  ],
  [
    '632',
    'Charges locatives des immeubles non affectés aux activités professionnelles',
  ],
  ['633', 'Jetons de présence'],
  ['634', 'Pertes sur créances irrécouvrables'],
  ['635', 'Quote-part de résultat sur opérations faites en commun'],
  [
    '636',
    'Charges nettes sur cessions d’immobilisations et autres pertes ordinaires',
  ],
  ['637', 'Réduction de valeur'],
  ['638', 'Charges diverses ordinaires'],
  ['64', 'Charges de personnel'],
  ['640', 'Salaires'],
  ['6400', 'Salaires de base'],
  ['6401', 'Heures supplémentaires'],
  ['6402', 'Primes'],
  ['6403', 'Gratifications'],
  ['6404', 'Avantages en nature'],
  ['6409', 'Autres compléments de salaires'],
  ['642', 'Appointements et compléments'],
  ['643', 'Indemnités représentatives de frais'],
  ['644', 'Commissions au personnel'],
  ['645', 'Rémunérations des administrateurs, gérants et associés'],
  ['646', 'Charges connexes aux rémunérations'],
  ['647', 'Charges sociales légales'],
  ['6470', 'Cotisations de sécurité sociale sur salaires'],
  ['6472', 'Cotisations de sécurité sociale sur appointements'],
  ['6476', 'Prestations directes'],
  ['648', 'Charges de personnel liées à une modification comptable'],
  ['649', 'Autres charges de personnel et charges sociales'],
  ['65', 'Charges financières'],
  ['651', "Charges d'intérêts"],
  ['6511', 'Intérêts des emprunts et dettes'],
  ['6515', 'Intérêts des comptes courants et dépôts créditeurs'],
  ['6516', 'Intérêts bancaires et opérations de financement'],
  ['653', 'Pertes sur créances liées à des participations'],
  ['654', 'Escomptes accordés'],
  ['655', 'Pertes de change'],
  ['656', 'Charges nettes sur cessions de valeurs mobilières'],
  ['657', 'Autres charges financières'],
  ['66', 'Impôts, taxes et versements assimilés'],
  ['661', 'Impôts, taxes et versements assimilés sur rémunérations'],
  ['665', 'Autres impôts, taxes et versements assimilés'],
  ['67', 'Pertes extraordinaires'],
  ['68', 'Dotations aux amortissements et aux provisions'],
  [
    '681',
    "Dotations aux amortissements et provisions - charges d'exploitation",
  ],
  [
    '6811',
    'Dotations aux amortissements des immobilisations incorporelles et corporelles',
  ],
  ['6815', "Dotations aux provisions pour risques et charges d'exploitation"],
  ['6816', 'Dotations aux provisions pour dépréciation des actifs courants'],
  ['686', 'Dotations aux amortissements et provisions - charges financières'],
  ['69', 'Impôts sur les bénéfices'],
  ['691', 'Impôts sur les bénéfices'],

  [
    '70',
    'Ventes de produits fabriqués, prestations de services et marchandises',
  ],
  ['701', 'Ventes de produits finis'],
  ['7011', 'Produits finis achevés'],
  ['7012', 'Produits finis non achevés'],
  ['702', 'Ventes de produits intermédiaires'],
  ['703', 'Ventes de produits résiduels'],
  ['704', 'Travaux'],
  ['705', 'Études et prestations de services'],
  ['706', 'Produits des activités annexes'],
  ['707', 'Ventes de marchandises'],
  ['708', 'Ventes liées à une modification comptable ou activité abandonnée'],
  ['709', "Rabais, remises et ristournes accordés par l'entreprise"],
  ['7091', 'Rabais sur ventes de produits finis'],
  ['7094', 'Rabais sur travaux'],
  ['7095', 'Rabais sur études et prestations'],
  ['7097', 'Rabais sur ventes de marchandises'],
  ['71', 'Production stockée ou déstockage'],
  ['713', 'Variation des stocks - en-cours et produits'],
  ['7133', 'Variation des en-cours de production de biens'],
  ['7134', 'Variation des en-cours de production de services'],
  ['7135', 'Variation des stocks de produits'],
  ['72', 'Production immobilisée'],
  ['721', 'Immobilisations incorporelles produites'],
  ['722', 'Immobilisations corporelles produites'],
  ['728', 'Production immobilisée liée à une modification comptable'],
  ['73', 'Produits divers ordinaires'],
  [
    '731',
    'Redevances pour concessions, brevets, licences et droits similaires',
  ],
  ['732', 'Revenus des immeubles non affectés aux activités professionnelles'],
  ['733', "Jetons de présence et rémunérations d'administrateurs"],
  ['734', 'Ristournes perçues des coopératives'],
  ['735', 'Quote-part de résultat sur opérations faites en commun'],
  [
    '736',
    'Produits nets sur cessions d’immobilisations et autres gains ordinaires',
  ],
  ['738', 'Autres produits divers ordinaires'],
  ['74', "Subventions d'exploitation et d'équilibre"],
  ['741', "Subventions d'exploitation"],
  ['745', "Subventions d'équilibre"],
  ['75', 'Produits financiers'],
  ['751', 'Produits des participations'],
  ['752', 'Produits des autres immobilisations financières'],
  ['753', 'Revenus des autres créances'],
  ['754', 'Escomptes obtenus'],
  ['755', 'Gains de change'],
  ['756', 'Produits nets sur cessions de valeurs mobilières'],
  ['757', 'Autres produits financiers'],
  ['77', 'Gains extraordinaires'],
  ['78', 'Reprises sur amortissements et provisions'],
  ['781', 'Reprises sur amortissements et provisions - exploitation'],
  ['786', 'Reprises sur provisions - financier'],
  ['79', 'Transferts de charges'],
];

function classify(
  code: string,
): Pick<TunisianChartAccount, 'type' | 'normalBalance'> {
  const first = code[0];
  let type: LedgerAccountType;
  if (first === '1')
    type =
      code.startsWith('10') ||
      code.startsWith('11') ||
      code.startsWith('12') ||
      code.startsWith('13') ||
      code.startsWith('14')
        ? LedgerAccountType.Equity
        : LedgerAccountType.Liability;
  else if (first === '2' || first === '3') type = LedgerAccountType.Asset;
  else if (first === '4')
    type =
      code.startsWith('40') || code.startsWith('43') || code.startsWith('48')
        ? LedgerAccountType.Liability
        : LedgerAccountType.Asset;
  else if (first === '5')
    type = code.startsWith('50')
      ? LedgerAccountType.Liability
      : LedgerAccountType.Asset;
  else if (first === '6') type = LedgerAccountType.Expense;
  else if (first === '7') type = LedgerAccountType.Revenue;
  else type = LedgerAccountType.OffBalanceSheet;

  const contraAsset = /^(28|29|39|49|59)/.test(code);
  const normalBalance =
    contraAsset ||
    [
      LedgerAccountType.Liability,
      LedgerAccountType.Equity,
      LedgerAccountType.Revenue,
    ].includes(type)
      ? NormalBalance.Credit
      : NormalBalance.Debit;
  return { type, normalBalance };
}

export const TUNISIAN_NC01_CHART: TunisianChartAccount[] = rows.map(
  ([code, name]) => {
    const parent =
      rows
        .filter(
          ([candidate]) =>
            code.startsWith(candidate) && candidate.length < code.length,
        )
        .sort((a, b) => b[0].length - a[0].length)[0]?.[0] ?? null;
    const allowsPosting = !rows.some(
      ([candidate]) =>
        candidate.length > code.length && candidate.startsWith(code),
    );
    return { code, name, parentCode: parent, allowsPosting, ...classify(code) };
  },
);
